### ISSUE TITLE
Workflow for metadata injections within B2SAFE

### ISSUE THREAD

**Issue by pdonorio** [EUDAT-B2STAGE/http-api#16]
We should move the logic of the graph operations inside irods irules

**Comment by pdonorio** [comment]
discussion tomorrow with @muccix and @mdantonio

**Comment by muccix** [comment]
I paste here my comments on the last slide (more a request for confirmation of my understanding then an actual comment):

PRE: before saving the entity in iRODS the POST /api endpoint is called to retrieve the uuid

DO: as the entity is saved on iRODS the PID is generated with the HTTP API url previously got from the POST request

POST: after the DO, PUT /api/uuid is called to update the neo4J object with PID and metadata

**Comment by pdonorio** [comment]
> more a request for confirmation of my understanding 

It's all correct. The POST action should be a celery task in background.

**Comment by pdonorio** [comment]
The `POST` action, which issues the `UUID` for a new empty dataobject is now available as `/api/internals/metadataobj`.

To sum it up, things needed to fully implement this task:

- [ ] irods irules in our docker version of irods [#17]
- [ ] a celery task for reading metadata [#18] which will be used to inject the graph inside the `PUT` method
- [ ] authentication based on `roles`: we are yet missing the decorator to decide the list of roles requested. [ EUDAT-B2STAGE/http-api-base#29 ]
- [ ] internal endpoints generalization (and roles association) [ EUDAT-B2STAGE/http-api-base#30 ]

**Comment by muccix** [comment]
After a short talk with Claudio Cacciari I understand that the PID request is not done as the object is uploaded in iRODS: it can be done also later on.
So we could change the workflow so that the POST /api endpoint to retrieve the uuid is called by B2SAFE just before requesting the PID (not directly triggered by the iRODS rule).
Than the PUT /api/uuid is called to update the neo4J node.

**Comment by pdonorio** [comment]
No time/effort for the first stable release.
